// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-transactions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}

// src/lib/mcp/tools/list-transactions.ts
var list_transactions_default = defineTool({
  name: "list_transactions",
  title: "Listar lan\xE7amentos",
  description: "Lista lan\xE7amentos financeiros do usu\xE1rio autenticado, com filtros opcionais por intervalo de datas, tipo, categoria e status.",
  inputSchema: {
    start_date: z.string().optional().describe("Data inicial YYYY-MM-DD (inclusive)"),
    end_date: z.string().optional().describe("Data final YYYY-MM-DD (inclusive)"),
    type: z.enum(["income", "expense"]).optional().describe("Tipo de lan\xE7amento"),
    category: z.string().optional().describe("Categoria exata"),
    status: z.enum(["pending", "paid"]).optional(),
    limit: z.number().int().min(1).max(500).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, type, category, status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = supabaseForUser(ctx).from("transactions").select("id,date,description,category,type,amount,status,payment_date,credit_card,installments,current_installment").eq("user_id", ctx.getUserId()).order("date", { ascending: false }).limit(limit);
    if (start_date) q = q.gte("date", start_date);
    if (end_date) q = q.lte("date", end_date);
    if (type) q = q.eq("type", type);
    if (category) q = q.eq("category", category);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-transaction.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
var add_transaction_default = defineTool2({
  name: "add_transaction",
  title: "Adicionar lan\xE7amento",
  description: "Cria um novo lan\xE7amento financeiro (receita ou despesa) para o usu\xE1rio autenticado.",
  inputSchema: {
    date: z2.string().describe("Data do lan\xE7amento YYYY-MM-DD"),
    description: z2.string().min(1),
    category: z2.string().min(1),
    type: z2.enum(["income", "expense"]),
    amount: z2.number().positive(),
    status: z2.enum(["pending", "paid"]).default("pending"),
    payment_date: z2.string().optional().describe("Data de pagamento YYYY-MM-DD"),
    credit_card: z2.string().optional(),
    installments: z2.number().int().min(1).optional(),
    current_installment: z2.number().int().min(1).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("transactions").insert({ ...input, user_id: ctx.getUserId() }).select().single();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Lan\xE7amento criado: ${data.id}` }],
      structuredContent: { transaction: data }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "Listar categorias",
  description: "Lista as categorias configuradas pelo usu\xE1rio (receitas e despesas).",
  inputSchema: {
    type: z3.enum(["income", "expense"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = supabaseForUser(ctx).from("user_categories").select("id,name,type").eq("user_id", ctx.getUserId()).order("name");
    if (type) q = q.eq("type", type);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/monthly-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
var monthly_summary_default = defineTool4({
  name: "monthly_summary",
  title: "Resumo mensal",
  description: "Retorna totais de receitas, despesas, saldo e gasto por categoria para um m\xEAs (YYYY-MM). Usa a data de pagamento quando presente, caso contr\xE1rio a data do lan\xE7amento.",
  inputSchema: {
    month: z4.string().regex(/^\d{4}-\d{2}$/).describe("M\xEAs no formato YYYY-MM")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const start = `${month}-01`;
    const [y, m] = month.split("-").map(Number);
    const nextMonth = m === 12 ? `${y + 1}-01-01` : `${y}-${String(m + 1).padStart(2, "0")}-01`;
    const { data, error } = await supabaseForUser(ctx).from("transactions").select("date,payment_date,type,category,amount,status").eq("user_id", ctx.getUserId());
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    let income = 0;
    let expense = 0;
    const byCategory = {};
    for (const t of data ?? []) {
      const ref = t.payment_date || t.date;
      if (!ref || ref < start || ref >= nextMonth) continue;
      const amt = Number(t.amount) || 0;
      if (t.type === "income") income += amt;
      else if (t.type === "expense") {
        expense += amt;
        byCategory[t.category] = (byCategory[t.category] || 0) + amt;
      }
    }
    const topCategories = Object.entries(byCategory).sort((a, b) => b[1] - a[1]).map(([category, total]) => ({ category, total }));
    const summary = { month, income, expense, balance: income - expense, expense_by_category: topCategories };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-credit-cards.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
var list_credit_cards_default = defineTool5({
  name: "list_credit_cards",
  title: "Listar cart\xF5es",
  description: "Lista os cart\xF5es de cr\xE9dito cadastrados pelo usu\xE1rio e seus limites.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("user_credit_cards").select("id,name,card_limit").eq("user_id", ctx.getUserId()).order("name");
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { credit_cards: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nhlznqxggksofmgwkhaq";
var mcp_default = defineMcp({
  name: "controle-financeiro-mcp",
  title: "Controle Financeiro",
  version: "0.1.0",
  instructions: "Ferramentas para consultar e gerenciar lan\xE7amentos financeiros pessoais do usu\xE1rio. Use `list_transactions` e `monthly_summary` para ler dados, `add_transaction` para criar novos lan\xE7amentos, e `list_categories` / `list_credit_cards` para descobrir valores v\xE1lidos antes de criar lan\xE7amentos.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_transactions_default,
    add_transaction_default,
    list_categories_default,
    monthly_summary_default,
    list_credit_cards_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
